import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import { ThemeProvider } from "@/components/global/theme-provider";
import Footer from "@/components/layout/footer";
import { UserProvider } from "@/components/context/user-provider";
import { ShoppingCartProvider } from "@/components/context/cart-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ShoppingCartProvider>
            <ThemeProvider attribute="class">
              <Navbar />
              {children}
              <Footer />
            </ThemeProvider>
          </ShoppingCartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
